app/account/urls.py
from django.urls import path

from account.views import SignUpView, UserActivateView, ProfileView, CustomPasswordChangeView

app_name = 'account'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>', UserActivateView.as_view(), name='activate'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),
]

app/currency/api/v1/urls.py
from rest_framework.routers import DefaultRouter

from app.currency.api.v1.views import (RateViewSet, SourceViewSet, ContactUsViewSet)

router = DefaultRouter(trailing_slash=False)
router.register('rates/', RateViewSet, basename='rates')
router.register('source/', SourceViewSet, basename='source')
router.register('contactus/', ContactUsViewSet, basename='contactus')

app_name = 'currency_api'

urlpatterns = [
] + router.urls

app/currency/urls.py
from django.urls import path
# from django.conf.urls.static import static
# from django.conf import settings
from currency.views import (
    RateListView,
    RateCreateView,
    RateUpdateView,
    RateDetailView,
    RateDeleteView,
    SourceListView,
    SourceCreateView,
    SourceUpdateView,
    SourceDetailView,
    SourceDeleteView,
    ContactusListView,
    ContactusCreateView,
    ContactusUpdateView,
    ContactusDetailView,
    ContactusDeleteView,
)

app_name = 'currency'

urlpatterns = [
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),

    path('source/list/', SourceListView.as_view(), name='source-list'),
    path('source/create/', SourceCreateView.as_view(), name='source-create'),
    path('source/update/<int:pk>/', SourceUpdateView.as_view(), name='source-update'),
    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),
    path('source/delete/<int:pk>/', SourceDeleteView.as_view(), name='source-delete'),

    path('contactus/list/', ContactusListView.as_view(), name='contactus'),
    path('contactus/create/', ContactusCreateView.as_view(), name='contactus-create'),
    path('contactus/update/<int:pk>/', ContactusUpdateView.as_view(), name='contactus-update'),
    path('contactus/details/<int:pk>/', ContactusDetailView.as_view(), name='contactus-details'),
    path('contactus/delete/<int:pk>/', ContactusDeleteView.as_view(), name='contactus-delete'),
]

app/settings/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
# from currency.views import ProfileView, CustomPasswordChangeView

schema_view = get_schema_view(
   openapi.Info(
      title="Currency",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('currency/', include('currency.urls')),
    path('api/v1/currency/', include('currency.api.v1.urls')),
    path('account/', include('account.urls')),
    path('api/v1/account/', include('currency.api.v1.urls')),

    path('api/swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('api/swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('', TemplateView.as_view(template_name='index.html'), name='index')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from django.db import models
from django.core.validators import EmailValidator
from currency.choices import RateCurrencyChoices
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _


def logo_path(instance, filename):
    return f'logo/source_{instance.id}/{filename}'


class Rate(models.Model):
    buy = models.DecimalField(_('Buy'), max_digits=6, decimal_places=2)
    sell = models.DecimalField(_('Sell'), max_digits=6, decimal_places=2, validators=[])
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    currency = models.PositiveSmallIntegerField(_('Currency'),
                                                choices=RateCurrencyChoices.choices,
                                                default=RateCurrencyChoices.USD
                                                )
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')

    class Meta:
        verbose_name = ('Rate')
        verbose_name_plural = ('Rates')


class Contact_us(models.Model):
    email_from = models.CharField(_('Email'), max_length=256, validators=[EmailValidator])
    subject = models.CharField(_('Subject'), max_length=100)
    message = models.CharField(_('Message'), max_length=300)

    class Meta:
        verbose_name = ('Contact Us')
        verbose_name_plural = ('Contact Us')


class Source(models.Model):
    name = models.CharField(_('Name'), max_length=64)
    code_name = models.CharField(_('Code Name'), max_length=64, unique=True)
    source_url = models.URLField(_('URL'), max_length=255)
    phone = models.CharField(_('Phone'), max_length=13)
    logo = models.FileField(
        _('Logo'),
        default=None,
        null=True,
        blank=True,
        upload_to=logo_path
    )

    @property
    def logo_url(self) -> str:
        if self.logo:
            return self.logo.url

        return static('source/6_custom_icons_02.png')

    class Meta:
        verbose_name = ('Source')
        verbose_name_plural = ('Sources')

    def __str__(self):
        return self.name


class RequestResponseLog(models.Model):
    path = models.CharField(max_length=100)
    request_method = models.CharField(max_length=100)
    time = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

app/currency/forms.py
from django import forms

from currency.models import Rate, Source, Contact_us


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sell',
            'currency',
            'source'
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'name',
            'source_url',
            'phone',
            'logo'
        )


class ContactusForm(forms.ModelForm):
    class Meta:
        model = Contact_us
        fields = (
            'email_from',
            'subject',
            'message',
        )

app/currency/api/v1/views.py
from rest_framework import viewsets

from currency.api.v1.serializers import RateSerializer, SourceSerializer, ContactUsSerializer
from currency.models import Rate, Source, Contact_us
from rest_framework.renderers import JSONRenderer
from rest_framework_xml.renderers import XMLRenderer
from rest_framework_yaml.renderers import YAMLRenderer

from django_filters import rest_framework as alias_filters
from rest_framework import filters

# from rest_framework import filters as rest_framework_filters

from app.currency.api.v1.paginators import RatePagination, SourcePagination, ContactUsPagination
from currency.api.v1.filters import RateFilter, SourceFilter, ContactUsFilter


class RateViewSet(viewsets.ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = RatePagination
    filter_backends = (
        alias_filters.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )
    filterset_class = RateFilter
    ordering_fields = ('buy', 'sell', 'created')


class SourceViewSet(viewsets.ModelViewSet):
    queryset = Source.objects.all().order_by('-id')
    serializer_class = SourceSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = SourcePagination
    filter_backends = (
        alias_filters.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )
    search_fields = ['name', 'code_name']
    filterset_class = SourceFilter
    ordering_fields = ('id',)


class ContactUsViewSet(viewsets.ModelViewSet):
    queryset = Contact_us.objects.all().order_by('-id')
    serializer_class = ContactUsSerializer
    renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = ContactUsPagination
    filter_backends = (
        alias_filters.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )
    filterset_class = ContactUsFilter
    ordering_fields = ('id',)

app/currency/views.py
from django.conf import settings
from django.urls import reverse_lazy
from django.http.response import HttpResponse, HttpResponseRedirect, Http404   # noqa F401
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    CreateView, UpdateView,
    DetailView, DeleteView, TemplateView
)
from django_filters.views import FilterView
from currency.models import Rate, Contact_us, Source
from currency.forms import RateForm, SourceForm, ContactusForm
from currency.tasks import send_email_from_background

from app.currency.filters import RateFilter, SourceFilter, ContactusFilter


class SuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class RateListView(FilterView):
    queryset = Rate.objects.all().select_related('source')
    template_name = 'rate_list.html'
    paginate_by = 10
    filterset_class = RateFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['filter_params'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class RateCreateView(CreateView):
    form_class = RateForm
    template_name = 'rate_create.html'
    success_url = reverse_lazy('currency:rate-list')


class RateUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    model = Rate
    form_class = RateForm
    template_name = 'rate_update.html'
    success_url = reverse_lazy('currency:rate-list')

    def get_queryset(self):
        queryset = Rate.objects.all()
        return queryset


class RateDetailView(LoginRequiredMixin, DetailView):
    model = Rate
    template_name = 'rate_details.html'

    def get_queryset(self):
        queryset = Rate.objects.all()
        return queryset


class RateDeleteView(LoginRequiredMixin, SuperuserRequiredMixin, DeleteView):
    model = Rate
    template_name = 'rate_delete.html'
    success_url = reverse_lazy('currency:rate-list')

    def get_queryset(self):
        queryset = Rate.objects.all()
        return queryset


class SourceListView(FilterView):
    queryset = Source.objects.all()
    template_name = 'source_list.html'
    paginate_by = 10
    filterset_class = SourceFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['filter_params'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class SourceCreateView(CreateView):
    form_class = SourceForm
    template_name = 'source_create.html'
    success_url = reverse_lazy('currency:source-list')


class SourceUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    model = Source
    form_class = SourceForm
    template_name = 'source_update.html'
    success_url = reverse_lazy('currency:source-list')

    def get_queryset(self):
        queryset = Source.objects.all()
        return queryset


class SourceDetailView(LoginRequiredMixin, DetailView):
    model = Source
    template_name = 'source_details.html'

    def get_queryset(self):
        queryset = Source.objects.all()
        return queryset


class SourceDeleteView(LoginRequiredMixin, SuperuserRequiredMixin, DeleteView):
    model = Source
    template_name = 'source_delete.html'
    success_url = reverse_lazy('currency:source-list')

    def get_queryset(self):
        queryset = Source.objects.all()
        return queryset


class ContactusListView(FilterView):
    queryset = Contact_us.objects.all()
    template_name = 'contact_us.html'
    paginate_by = 10
    filterset_class = ContactusFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['filter_params'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        return context


class ContactusCreateView(CreateView):
    form_class = ContactusForm
    template_name = 'contactus_create.html'
    success_url = reverse_lazy('currency:contactus')

    def _send_mail(self):
        recipient = settings.DEFAULT_FROM_EMAIL    # noqa F841
        subject = 'User Contact Us'
        body = f'''
                Email to reply: {self.object.email_from}.
                Subject Subject: {self.object.subject}.
                Body: {self.object.message}.
                '''
        send_email_from_background.delay(subject, body)

    def form_valid(self, form):
        redirect = super().form_valid(form)
        self._send_mail()
        return redirect


class ContactusUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    model = Contact_us
    form_class = ContactusForm # noqa F401
    template_name = 'contactus_update.html'
    success_url = reverse_lazy('currency:contactus')


class ContactusDetailView(LoginRequiredMixin, DetailView):
    model = Contact_us
    template_name = 'contactus_details.html'


class ContactusDeleteView(LoginRequiredMixin, SuperuserRequiredMixin, DeleteView):
    model = Contact_us
    template_name = 'contactus_delete.html'
    success_url = reverse_lazy('currency:contactus')


class IndexView(TemplateView):
    template_name = 'index.html'

app/currency/templates/contact_us.html
{% extends 'base.html' %}

{% block title %}
    Contact Us
{% endblock title %}

{% block content %}

    <a href="{% url 'currency:contactus-create' %}">Create</a><br>
    <form method = "get" >
         {{filter.form.as_p}}
         <button type = "submit">Filter</button >
    </form >
    <table>
        <tr>
            <th>ID</th>
            <th>Emails from</th>
            <th>Subject</th>
            <th>Message</th>
        </tr>

        {% for contact_us in object_list %}
        <tr>
            <td>{{ contact_us.id }}</td>
            <td>{{ contact_us.email_from }}</td>
            <td>{{ contact_us.subject }}</td>
            <td>{{ contact_us.message }}</td>
            <td><a href="{% url 'currency:contactus-update' contact_us.id %}">Edit</a></td>
            <td><a href="{% url 'currency:contactus-details' contact_us.id %}">Details</a></td>
            <td><a href="{% url 'currency:contactus-delete' contact_us.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
{% include 'includes/pagination.html' %}
{% endblock content %}

app/currency/templates/contactus_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Create Contact Us
{% endblock title %}

{% block content %}
    Create Contact Us form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/contactus_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete Contact Us Form
{% endblock title %}

{% block content %}
    Are you sure you want to delete Form with id: {{ object.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/contactus_details.html
{% extends 'base.html' %}

{% block title %}
    Contact Us Form Details
{% endblock title %}

{% block content %}
        <strong>ID:</strong> {{ contact_us.id }}<br>
        <strong>Emails:</strong> {{ contact_us.email_from }}<br>
        <strong>Subject:</strong>{{ contact_us.subject }}<br>
        <strong>Message:</strong> {{ contact_us.message }}<br>
{% endblock content %}

app/currency/templates/contactus_update.html
{% extends 'base.html' %}

{% block title %}
    Update Contact Us Form
{% endblock title %}

{% block content %}
    Update Contact Us Form

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Edit</button>
    </form>

{% endblock content %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock title %}

{% block content %}
    <h1>Hello World!</h1>
{% endblock content %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Create rate
{% endblock title %}

{% block content %}
    Create rate form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete rate
{% endblock title %}

{% block content %}
    Are you sure you want to delete rate with id: {{ object.id }}?

    <form method="post">
        {% csrf_token %}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}

{% block title %}
    Rates
{% endblock title %}

{% block content %}

{% if request.user.is_superuser or request.user.is_authenticated %}
    <a href="{% url 'currency:rate-create' %}">Create</a><br>
    <form method = "get" >
         {{filter.form.as_p}}
         <button type = "submit">Filter</button >
    </form >
{% else %}

{% endif %}

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            {% if request.user.is_superuser or request.user.is_authenticated %}
                <th scope="col">ID</th>
                <th scope="col">Buy</th>
                <th scope="col">Sell</th>
                <th scope="col">Currency</th>
                <th scope="col">Source</th>
                <th scope="col">Actions</th>
            {% else %}
                <th scope="col">ID</th>
                <th scope="col">Buy</th>
                <th scope="col">Sell</th>
                <th scope="col">Currency</th>
                <th scope="col">Source</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for rate in object_list %}
    <tr>
        <td>{{ rate.id }}</td>
        <td>{{ rate.buy }}</td>
        <td>{{ rate.sell }}</td>
        <td>{{ rate.get_currency_display }}</td>
        <td>{{ rate.source }}</td>

        {% if request.user.is_superuser %}
            <td>
                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'currency:rate-update' rate.id %}">Edit</a>
                        <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                        <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.id %}">Delete</a>
                    </div>
                </div>
            </td>
        {% elif request.user.is_authenticated %}
            <td>
                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'currency:rate-details' rate.id %}">Details</a>
                    </div>
                </div>
            </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>

{% include 'includes/pagination.html' %}
{% endblock content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Update rate
{% endblock title %}

{% block content %}
    Update rate form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Edit</button>
    </form>

{% endblock content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Create source
{% endblock title %}

{% block content %}
    Create source form

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

app/currency/templates/source_details.html
{% extends 'base.html' %}

{% block title %}
    Source Details
{% endblock title %}

{% block content %}
<br>
<img src="{{ source.logo_url }}" alt="logo" width="25px" height="25px">
        <strong>ID:</strong> {{ source.id }}<br>
        <strong>Name:</strong> {{ source.name }}<br>
        <strong>URL:</strong> {{ source.source_url }}<br>
        <strong>Phone:</strong> {{ source.phone }}<br>
{% endblock content %}

app/currency/templates/source_list.html
{% extends 'base.html' %}

{% block title %}
    Rates
{% endblock title %}

{% block content %}

{% if request.user.is_superuser or request.user.is_authenticated %}
    <a href="{% url 'currency:source-create' %}">Create</a><br>
    <form method = "get" >
         {{filter.form.as_p}}
         <button type = "submit">Filter</button >
    </form >
{% else %}

{% endif %}

<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            {% if request.user.is_superuser or request.user.is_authenticated %}
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Actions</th>
            {% else %}
                <th scope="col">ID</th>
                <th scope="col">Name</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for source in object_list %}
    <tr>
        <td>{{ source.id }}</td>
        <td>{{ source.name }}</td>
        {% if request.user.is_superuser %}
            <td>
                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'currency:source-update' source.id %}">Edit</a>
                        <a class="dropdown-item" href="{% url 'currency:source-details' source.id %}">Details</a>
                        <a class="dropdown-item" href="{% url 'currency:source-delete' source.id %}">Delete</a>
                    </div>
                </div>
            </td>
        {% elif request.user.is_authenticated %}
            <td>
                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'currency:source-details' source.id %}">Details</a>
                    </div>
                </div>
            </td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% include 'includes/pagination.html' %}
{% endblock content %}

app/currency/templates/source_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Update source
{% endblock title %}

{% block content %}
    Update source form
    <br>
    <img src="{{ source.logo_url }}" alt="logo" width="25px" height="25px">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Edit</button>
    </form>

{% endblock content %}